package com.zhj.test.mapper;

import com.zhj.test.model.Cnip;
import com.zhj.test.model.CnipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CnipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    long countByExample(CnipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    int deleteByExample(CnipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    int deleteByPrimaryKey(Long start);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    int insert(Cnip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    int insertSelective(Cnip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    List<Cnip> selectByExampleWithRowbounds(CnipExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    List<Cnip> selectByExample(CnipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    Cnip selectByPrimaryKey(Long start);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") Cnip record, @Param("example") CnipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    int updateByExample(@Param("record") Cnip record, @Param("example") CnipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    int updateByPrimaryKeySelective(Cnip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnip
     *
     * @mbg.generated Tue Dec 15 09:44:19 CST 2020
     */
    int updateByPrimaryKey(Cnip record);
}